version: '3.7'

networks:
  user:
    driver: ${NETWORKS_DRIVER}

services:
  postgres:
    image: user/postgres
    container_name: postgres
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "2000:${POSTGRES_PORT}"
    networks:
      - user